### ISSUE TITLE
why you dont publish on atmosphere!?

### ISSUE THREAD

**Issue by stefanocudini** [pfafman/meteor-photo-uploader#1]
is very simple

mrt publish .

**Comment by pfafman** [comment]
Cause I have not had the time to update this since transition to Blaze.

**Comment by stefanocudini** [comment]
upgrade to blaze is less complicated than you may think :)

**Comment by pfafman** [comment]
I have rewritten this see [PhotoUp](https://github.com/pfafman/meteor-photo-up)
