### ISSUE TITLE
erro on Meteor 0.8.2

### ISSUE THREAD

**Issue by stefanocudini** [pfafman/meteor-photo-uploader#2]
Exception from Deps recompute function: Error: Can't find template, helper or data context key: photoUpload

**Comment by pfafman** [comment]
Needs to be modified for Blaze.  Handlebars to UI and the like

**Comment by stefanocudini** [comment]
I was checking the code is weird .. the template is defined normally!

**Comment by stefanocudini** [comment]
I was trying to create a single package for the management of the profile picture in the easiest way possible, the client and server management 

not using collectionFS because I consider oversized for this simple purpose! 

What do you think?

for upload and file storing I'm just write this:
https://github.com/stefanocudini/meteor-simple-file-uploader

**Comment by pfafman** [comment]
I have rewritten this see [PhotoUp](https://github.com/pfafman/meteor-photo-up)

**Comment by stefanocudini** [comment]
@mstn FYI
