### ISSUE TITLE
object is not a function

### ISSUE THREAD

**Issue by mikeadeleke** [pfafman/meteor-photo-uploader#3]
My issues is that I continue to get an error saying that the object is not a function. I'm wondering whether I need to have an argument passed in the complete the function and did not see anything on the README. 
![screenshot 2014-08-18 15 56 10](https://cloud.githubusercontent.com/assets/3124481/3957058/15ea86a0-2712-11e4-874f-99081089e313.png)

Template.listingSubmit.events({
    'submit form': function(e) {
        e.preventDefault();

```
    var listing = {
        address: $(e.target).find('[name=address]').val(),
        price: $(e.target).find('[name=price]').val(),
        owner: $(e.target).find('[name=owner]').val()
    }

listing._id = Listings.insert(listing);
Router.go('listingPage', listing); }
```

});

Uploader = new PhotoUploader({uploadButtonLabel: "Upload"})

![screenshot 2014-08-18 15 59 22](https://cloud.githubusercontent.com/assets/3124481/3957080/49a1bd42-2712-11e4-8989-2e3dd869030e.png)
![screenshot 2014-08-18 15 59 32](https://cloud.githubusercontent.com/assets/3124481/3957081/4cdf358e-2712-11e4-971d-45b9585e0400.png)
![screenshot 2014-08-18 15 59 45](https://cloud.githubusercontent.com/assets/3124481/3957082/4f467198-2712-11e4-959c-f456370faa36.png)

**Comment by pfafman** [comment]
This was an internal package I wrote and did not release to Atmosphere.  I have not messed with it since before meter 0.6 or so.  I have not had time to bring it up to date with the major changes in meteor.  Feel free to fork it and have fun.

**Comment by pfafman** [comment]
I have re-written.  See [PhotoUp](https://github.com/pfafman/meteor-photo-up)
